### ISSUE TITLE
Create endpoint for deleting solutions (content creator)

### ISSUE THREAD

**Issue by LarsVDriel** [Fontys-S6-maatwerk/SolutionsService#10]
What has to be done:
Create an endpoint for deleting an existing solution.

Why it has to be done:
So the users can delete their solution.

When the task is done:
The delete endpoint checks if the deletion is valid, the solution was deleted by the same user that created it, and if it is valid, the solution will be deleted.

**Comment by EGKangaroo** [comment]
Tested endpoint in swagger, it still works with the updated models
