### ISSUE TITLE
Create endpoint for deleting solutions (administrator)

### ISSUE THREAD

**Issue by LarsVDriel** [Fontys-S6-maatwerk/SolutionsService#11]
What has to be done:
Create an endpoint for deleting a new solution by an administrator.

Why it has to be done:
So the administrator can delete a specific solution.

When the task is done:
The delete endpoint is created and it validates that the request is valid. When it is valid the solution will be deleted.

**Comment by EGKangaroo** [comment]
Tested endpoint in swagger, it still works with the updated models
